"""
Aggregate every pilot result dump into paper-ready tables.

Reads data/pilot_v2_*/results.json (written by run_pilot_v2.py evaluate) and
emits:
  1. Main table: detector x model, semantic-subset AUC (mean +/- sd over seeds)
  2. Model characterization table: error rates, failure-mode mix, logprob AUC
  3. Access-tier frontier: best detector per access level per model
  4. LaTeX version of the main table

Usage:  python make_paper_tables.py [--out docs/RESULTS.md]
"""
import argparse
import json
from pathlib import Path

import numpy as np

# Display name -> (access tier, canonical row order)
ACCESS_TIER = {
    "Mean logprob": "logits",
    "Surface (lengths) [confound]": "confound",
    "Gen length only [confound]": "confound",
    "Tool one-hot [confound]": "confound",
    "Spectral per-layer (LMM)": "attention",
    "Spectral per-layer, gen span": "attention",
    "Spectral trajectory (SpRich)": "attention",
    "Spectral velocity": "attention",
    "Sym-Laplacian eig profile": "attention",
    "Sym-Laplacian eig profile, gen span": "attention",
    "Per-head fiedler_value (span)": "attention",
    "Per-head connectivity_ratio (span)": "attention",
    "Per-head spectral_entropy_norm (span)": "attention",
    "Per-head hfer (span)": "attention",
    "Per-head lambda_max (span)": "attention",
    "Per-head connectivity_ratio (span)": "attention",
    "Per-head all metrics (span)": "attention",
    "Per-head lambda_max dynamics": "attention",
    "Per-head lambda_max static+dynamics": "attention",
    "All attention-spectral combined": "attention",
    "LapEigvals (official code)": "attention",
    "Best single spectral (honest sweep)": "attention",
    "Hidden token-role [LR]": "hidden",
    "Hidden token-role [MLP]": "hidden",
    "Hidden Gram spectra (EigenScore)": "hidden",
    "Token-level probe (Obeso)": "hidden",
    "Residual dynamics (ICR-style)": "hidden",
    "Lookback Lens": "attention",
}

# Pretty model labels, in paper order
MODEL_LABELS = {
    "llama_32_1b": "Llama-3.2-1B / Glaive",
    "llama_32_3b": "Llama-3.2-3B / Glaive",
    "qwen35_2b": "Qwen3.5-2B / Glaive",
    "llama_32_1b_bfcl": "Llama-3.2-1B / BFCL-v4",
    "llama_32_3b_bfcl": "Llama-3.2-3B / BFCL-v4",
    "qwen35_2b_bfcl": "Qwen3.5-2B / BFCL-v4",
    "qwen3_17b_bfcl": "Qwen3-1.7B / BFCL-v4",
    "gemma3_1b": "Gemma-3-1B / Glaive",
    "minicpm5_2b_bfcl": "MiniCPM5-2B / BFCL-v4",
    "qwen35_4b_bfcl": "Qwen3.5-4B / BFCL-v4",
    "qwen35_08b_bfcl": "Qwen3.5-0.8B / BFCL-v4",
    "llama1b_live": "Llama-3.2-1B / BFCL-live",
    "minicpm5_2b_live": "MiniCPM5-2B / BFCL-live",
    "base_llama1b_bfcl": "Llama-3.2-1B / BFCL-v4 (all baselines)",
    "base_llama3b_bfcl": "Llama-3.2-3B / BFCL-v4 (all baselines)",
    "base_llama1b_glaive": "Llama-3.2-1B / Glaive (all baselines)",
}

ARCH_NOTE = {
    "llama_32_1b": "16 layers, 32 heads, full attention (GQA-8)",
    "llama_32_3b": "28 layers, 24 heads, full attention (GQA-8)",
    "qwen35_2b": "24 layers, 6 full-attention (hybrid gated-DeltaNet)",
    "qwen3_17b": "28 layers, 16 heads, all full attention (GQA-8)",
    "gemma3_1b": "26 layers, 4 heads/1 KV, 22 sliding-window + 4 full",
    "minicpm5_2b": "42 layers, 16 heads/2 KV, dense",
    "qwen35_4b": "32 layers, 16 heads, 8 full-attention (hybrid)",
    "qwen35_08b": "24 layers, 8 heads, 6 full-attention (hybrid)",
    "llama1b": "16 layers, 32 heads, dense GQA",
    "base_llama1b": "16 layers, 32 heads, dense GQA",
    "base_llama3b": "28 layers, 24 heads, dense GQA",
}


def fmt(vals):
    vals = [v for v in vals if v is not None and not np.isnan(v)]
    if not vals:
        return "--"
    return f"{np.mean(vals):.3f}±{np.std(vals):.3f}"


def mean_of(vals):
    vals = [v for v in vals if v is not None and not np.isnan(v)]
    return float(np.mean(vals)) if vals else float("nan")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="docs/RESULTS.md")
    ap.add_argument("--subset", choices=["semantic", "all"], default="semantic")
    args = ap.parse_args()

    runs = {}
    for p in sorted(Path("data").glob("pilot_v2_*/results.json")):
        tag = p.parent.name.replace("pilot_v2_", "")
        runs[tag] = json.loads(p.read_text(encoding="utf-8"))

    if not runs:
        print("no results.json found under data/pilot_v2_*/")
        return

    tags = [t for t in MODEL_LABELS if t in runs] + \
           [t for t in runs if t not in MODEL_LABELS]

    lines = ["# Results", "",
             f"Auto-generated by `make_paper_tables.py` "
             f"(subset: **{args.subset}**; pooled cross-fit AUC over "
             f"tool-level folds, mean±sd across seeds).", ""]

    # ── 1. model characterization ────────────────────────────────────────────
    lines += ["## 1. Benchmark / model characterization", "",
              "| Run | N | Halluc. rate | Failure modes | Architecture |",
              "|---|---|---|---|---|"]
    for t in tags:
        r = runs[t]
        modes = r.get("failure_modes", {})
        top = sorted(((v, k) for k, v in modes.items() if k not in
                      ("valid", "valid_nocall")), reverse=True)[:3]
        mode_str = ", ".join(f"{k} {v}" for v, k in top) or "--"
        lines.append(f"| {MODEL_LABELS.get(t, t)} | {r['n']} | "
                     f"{r['halluc_rate']:.3f} | {mode_str} | "
                     f"{ARCH_NOTE.get(t.replace('_bfcl', '').replace('_live', '').replace('_glaive', ''), '--')} |")
    lines.append("")

    # ── 2. main detector table ───────────────────────────────────────────────
    all_rows = [k for k in ACCESS_TIER
                if any(k in runs[t]["results"] for t in tags)]
    lines += ["## 2. Detector comparison", "",
              "| Detector | Access | " +
              " | ".join(MODEL_LABELS.get(t, t) for t in tags) + " |",
              "|---|---|" + "---|" * len(tags)]
    for row in all_rows:
        cells = []
        for t in tags:
            res = runs[t]["results"].get(row)
            cells.append(fmt(res[args.subset]) if res else "--")
        lines.append(f"| {row} | {ACCESS_TIER[row]} | " + " | ".join(cells) + " |")
    lines.append("")

    # ── 3. access-tier frontier ──────────────────────────────────────────────
    lines += ["## 3. Access-tier frontier (best detector per tier)", "",
              "| Run | logits only | attention only | + hidden states | "
              "confound floor |", "|---|---|---|---|---|"]
    for t in tags:
        res = runs[t]["results"]
        best = {}
        for tier in ("logits", "attention", "hidden", "confound"):
            cands = [(mean_of(v[args.subset]), k) for k, v in res.items()
                     if ACCESS_TIER.get(k) == tier and
                     not np.isnan(mean_of(v[args.subset]))]
            best[tier] = max(cands) if cands else (float("nan"), "--")
        cells = []
        for tier in ("logits", "attention", "hidden", "confound"):
            score, name = best[tier]
            cells.append("--" if np.isnan(score)
                         else f"{score:.3f} ({name.replace(' [confound]','')})")
        lines.append(f"| {MODEL_LABELS.get(t, t)} | " + " | ".join(cells) + " |")
    lines.append("")

    # ── 3b. cross-dataset transfer ───────────────────────────────────────────
    tf_files = sorted(Path("data").glob("pilot_v2_*/transfer_from_*.json"))
    if tf_files:
        lines += ["## 3b. Cross-dataset transfer (zero-shot, fixed model)", "",
                  "Detector trained on the *train* dump, applied unchanged to "
                  "the *test* dump. `Δ` is the drop versus that detector's "
                  "in-domain score on the test dump.", "",
                  "| Train → Test | Detector | Transfer AUC | In-domain AUC | Δ |",
                  "|---|---|---|---|---|"]
        for p in tf_files:
            test_tag = p.parent.name.replace("pilot_v2_", "")
            train_tag = p.name.replace("transfer_from_", "").replace(".json", "")
            tf = json.loads(p.read_text(encoding="utf-8"))
            indom = runs.get(test_tag, {}).get("results", {})
            for det, vals in tf.items():
                t_auc = mean_of(vals["semantic"])
                i_auc = mean_of(indom.get(det, {}).get("semantic", [np.nan]))
                delta = ("--" if np.isnan(i_auc) or np.isnan(t_auc)
                         else f"{t_auc - i_auc:+.3f}")
                lines.append(
                    f"| {MODEL_LABELS.get(train_tag, train_tag)} → "
                    f"{MODEL_LABELS.get(test_tag, test_tag)} | {det} | "
                    f"{fmt(vals['semantic'])} | "
                    f"{'--' if np.isnan(i_auc) else f'{i_auc:.3f}'} | {delta} |")
        lines.append("")

    # ── 4. LaTeX main table ──────────────────────────────────────────────────
    headline = ["Mean logprob", "Surface (lengths) [confound]",
                "LapEigvals (official code)", "Per-head all metrics (span)",
                "Per-head lambda_max (span)", "Hidden token-role [LR]"]
    lines += ["## 4. LaTeX (headline rows)", "", "```latex",
              "\\begin{tabular}{l" + "c" * len(tags) + "}",
              "\\toprule",
              "Detector & " + " & ".join(
                  MODEL_LABELS.get(t, t).replace("_", "\\_") for t in tags)
              + " \\\\", "\\midrule"]
    for row in headline:
        cells = []
        for t in tags:
            res = runs[t]["results"].get(row)
            cells.append(fmt(res[args.subset]).replace("±", " $\\pm$ ")
                         if res else "--")
        lines.append(row.replace("[confound]", "").replace("_", "\\_").strip()
                     + " & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "```", ""]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    # Summary only: non-UTF-8 consoles cannot encode the table characters.
    print(f"written -> {out}  ({len(lines)} lines, {len(tags)} runs)")
    for t in tags:
        run = runs[t]
        print(f"  - {MODEL_LABELS.get(t, t)}  N={run['n']}  "
              f"halluc={run['halluc_rate']:.3f}")


if __name__ == "__main__":
    main()
