"""
Aggregate every pilot result dump into paper-ready tables.

Reads data/pilot_v2_*/results.json (written by run_pilot_v2.py evaluate) and
emits:
  1. Main table: detector x model, semantic-subset AUC (mean +/- sd over seeds)
  2. Model characterization table: error rates, failure-mode mix, logprob AUC
  3. Access-tier frontier: best detector per access level per model
  4. LaTeX version of the main table

Usage:  python make_paper_tables.py [--out docs/RESULTS.md]
"""
import argparse
import json
from pathlib import Path

import numpy as np

# Display name -> (access tier, canonical row order)
ACCESS_TIER = {
    "Mean logprob": "logits",
    "Surface (lengths) [confound]": "confound",
    "Gen length only [confound]": "confound",
    "Tool one-hot [confound]": "confound",
    "Spectral per-layer (LMM)": "attention",
    "Spectral per-layer, gen span": "attention",
    "Spectral trajectory (SpRich)": "attention",
    "Spectral velocity": "attention",
    "Sym-Laplacian eig profile": "attention",
    "Sym-Laplacian eig profile, gen span": "attention",
    "Per-head fiedler_value (span)": "attention",
    "Per-head connectivity_ratio (span)": "attention",
    "Per-head spectral_entropy_norm (span)": "attention",
    "Per-head hfer (span)": "attention",
    "Per-head lambda_max (span)": "attention",
    "Per-head all metrics (span)": "attention",
    "Per-head lambda_max dynamics": "attention",
    "Per-head lambda_max static+dynamics": "attention",
    "All attention-spectral combined": "attention",
    "LapEigvals (official code)": "attention",
    "Best single spectral (honest sweep)": "attention",
    "Hidden token-role [LR]": "hidden",
    "Hidden token-role [MLP]": "hidden",
    "Hidden Gram spectra (EigenScore)": "hidden",
}

# Pretty model labels, in paper order
MODEL_LABELS = {
    "llama_32_1b": "Llama-3.2-1B / Glaive",
    "llama_32_3b": "Llama-3.2-3B / Glaive",
    "qwen35_2b": "Qwen3.5-2B / Glaive",
    "llama_32_1b_bfcl": "Llama-3.2-1B / BFCL-v4",
    "llama_32_3b_bfcl": "Llama-3.2-3B / BFCL-v4",
    "qwen35_2b_bfcl": "Qwen3.5-2B / BFCL-v4",
}

ARCH_NOTE = {
    "llama_32_1b": "16 layers, 32 heads, full attention (GQA-8)",
    "llama_32_3b": "28 layers, 24 heads, full attention (GQA-8)",
    "qwen35_2b": "24 layers, 6 full-attention (hybrid gated-DeltaNet)",
}


def fmt(vals):
    vals = [v for v in vals if v is not None and not np.isnan(v)]
    if not vals:
        return "--"
    return f"{np.mean(vals):.3f}±{np.std(vals):.3f}"


def mean_of(vals):
    vals = [v for v in vals if v is not None and not np.isnan(v)]
    return float(np.mean(vals)) if vals else float("nan")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="docs/RESULTS.md")
    ap.add_argument("--subset", choices=["semantic", "all"], default="semantic")
    args = ap.parse_args()

    runs = {}
    for p in sorted(Path("data").glob("pilot_v2_*/results.json")):
        tag = p.parent.name.replace("pilot_v2_", "")
        runs[tag] = json.loads(p.read_text(encoding="utf-8"))

    if not runs:
        print("no results.json found under data/pilot_v2_*/")
        return

    tags = [t for t in MODEL_LABELS if t in runs] + \
           [t for t in runs if t not in MODEL_LABELS]

    lines = ["# Results", "",
             f"Auto-generated by `make_paper_tables.py` "
             f"(subset: **{args.subset}**; pooled cross-fit AUC over "
             f"tool-level folds, mean±sd across seeds).", ""]

    # ── 1. model characterization ────────────────────────────────────────────
    lines += ["## 1. Benchmark / model characterization", "",
              "| Run | N | Halluc. rate | Failure modes | Architecture |",
              "|---|---|---|---|---|"]
    for t in tags:
        r = runs[t]
        modes = r.get("failure_modes", {})
        top = sorted(((v, k) for k, v in modes.items() if k not in
                      ("valid", "valid_nocall")), reverse=True)[:3]
        mode_str = ", ".join(f"{k} {v}" for v, k in top) or "--"
        lines.append(f"| {MODEL_LABELS.get(t, t)} | {r['n']} | "
                     f"{r['halluc_rate']:.3f} | {mode_str} | "
                     f"{ARCH_NOTE.get(t.replace('_bfcl',''), '--')} |")
    lines.append("")

    # ── 2. main detector table ───────────────────────────────────────────────
    all_rows = [k for k in ACCESS_TIER
                if any(k in runs[t]["results"] for t in tags)]
    lines += ["## 2. Detector comparison", "",
              "| Detector | Access | " +
              " | ".join(MODEL_LABELS.get(t, t) for t in tags) + " |",
              "|---|---|" + "---|" * len(tags)]
    for row in all_rows:
        cells = []
        for t in tags:
            res = runs[t]["results"].get(row)
            cells.append(fmt(res[args.subset]) if res else "--")
        lines.append(f"| {row} | {ACCESS_TIER[row]} | " + " | ".join(cells) + " |")
    lines.append("")

    # ── 3. access-tier frontier ──────────────────────────────────────────────
    lines += ["## 3. Access-tier frontier (best detector per tier)", "",
              "| Run | logits only | attention only | + hidden states | "
              "confound floor |", "|---|---|---|---|---|"]
    for t in tags:
        res = runs[t]["results"]
        best = {}
        for tier in ("logits", "attention", "hidden", "confound"):
            cands = [(mean_of(v[args.subset]), k) for k, v in res.items()
                     if ACCESS_TIER.get(k) == tier and
                     not np.isnan(mean_of(v[args.subset]))]
            best[tier] = max(cands) if cands else (float("nan"), "--")
        cells = []
        for tier in ("logits", "attention", "hidden", "confound"):
            score, name = best[tier]
            cells.append("--" if np.isnan(score)
                         else f"{score:.3f} ({name.replace(' [confound]','')})")
        lines.append(f"| {MODEL_LABELS.get(t, t)} | " + " | ".join(cells) + " |")
    lines.append("")

    # ── 4. LaTeX main table ──────────────────────────────────────────────────
    headline = ["Mean logprob", "Surface (lengths) [confound]",
                "LapEigvals (official code)", "Per-head all metrics (span)",
                "Per-head lambda_max (span)", "Hidden token-role [LR]"]
    lines += ["## 4. LaTeX (headline rows)", "", "```latex",
              "\\begin{tabular}{l" + "c" * len(tags) + "}",
              "\\toprule",
              "Detector & " + " & ".join(
                  MODEL_LABELS.get(t, t).replace("_", "\\_") for t in tags)
              + " \\\\", "\\midrule"]
    for row in headline:
        cells = []
        for t in tags:
            res = runs[t]["results"].get(row)
            cells.append(fmt(res[args.subset]).replace("±", " $\\pm$ ")
                         if res else "--")
        lines.append(row.replace("[confound]", "").replace("_", "\\_").strip()
                     + " & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "```", ""]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    print(f"\nwritten -> {out}")


if __name__ == "__main__":
    main()
