"""
Generate paper/iclr/generated_numbers.tex from the result files.

Every number in the paper resolves to a macro defined here, so no value is
typed by hand into the text. A macro that has no backing result file is
defined as \pending{...}, which renders visibly in the PDF, so a missing
experiment cannot be mistaken for a reported one.

Usage:  python analysis/make_paper_numbers.py
"""
import json
import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "paper" / "iclr" / "generated_numbers.tex"

# run tag -> macro infix
RUNS = {
    "llama_32_1b": "LlamaOneBGlaive",
    "llama_32_3b": "LlamaThreeBGlaive",
    "qwen35_2b": "QwenHybridGlaive",
    "gemma3_1b": "GemmaGlaive",
    "llama_32_1b_bfcl": "LlamaOneBBfcl",
    "llama_32_3b_bfcl": "LlamaThreeBBfcl",
    "qwen3_17b_bfcl": "QwenDenseBfcl",
}

# detector row -> macro infix
DETECTORS = {
    "Hidden token-role [LR]": "HiddenLR",
    "Hidden token-role [MLP]": "HiddenMLP",
    "Hidden Gram spectra (EigenScore)": "EigenScore",
    "LapEigvals (official code)": "LapEigvals",
    "Per-head all metrics (span)": "PerHeadAll",
    "Per-head fiedler_value (span)": "PerHeadFiedler",
    "Per-head lambda_max (span)": "PerHeadLmax",
    "Per-head connectivity_ratio (span)": "PerHeadConn",
    "Per-head spectral_entropy_norm (span)": "PerHeadEntropy",
    "Per-head hfer (span)": "PerHeadHfer",
    "Per-head lambda_max dynamics": "PerHeadDyn",
    "Per-head lambda_max static+dynamics": "PerHeadStaticDyn",
    "All attention-spectral combined": "AttnCombined",
    "Spectral per-layer (LMM)": "HeadAveragedLayer",
    "Spectral trajectory (SpRich)": "HeadAveragedTraj",
    "Spectral velocity": "HeadAveragedVel",
    "Sym-Laplacian eig profile": "SymEigProfile",
    "Mean logprob": "Logprob",
    "Surface (lengths) [confound]": "SurfaceConfound",
    "Gen length only [confound]": "LengthConfound",
    "Tool one-hot [confound]": "ToolConfound",
    "Best single spectral (honest sweep)": "HonestSweep",
}

SUBSETS = {"all": "All", "semantic": "Sem", "call_expected": "Call"}


def clean(name: str) -> str:
    """Macro-safe infix."""
    return re.sub(r"[^A-Za-z]", "", name)


def mean_sd(vals):
    vals = [v for v in vals if v is not None and not (isinstance(v, float) and np.isnan(v))]
    if not vals:
        return None
    return float(np.mean(vals)), float(np.std(vals))


def main():
    lines = [
        "% Auto-generated by paper/make_numbers.py. Do not edit by hand.",
        "% Macros without a backing result file expand to \\pending{}.",
        "\\providecommand{\\pending}[1]{\\textbf{[PENDING: #1]}}",
        "",
    ]
    defined = set()

    def define(name, value):
        if name in defined:
            return
        defined.add(name)
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    runs = {}
    for tag in RUNS:
        f = DATA / f"pilot_v2_{tag}" / "results.json"
        if f.exists():
            runs[tag] = json.loads(f.read_text(encoding="utf-8"))

    # ── per-run characterization ────────────────────────────────────────────
    for tag, infix in RUNS.items():
        r = runs.get(tag)
        if r is None:
            define(f"n{infix}", f"\\pending{{{tag} N}}")
            define(f"rate{infix}", f"\\pending{{{tag} rate}}")
            continue
        define(f"n{infix}", str(r["n"]))
        define(f"rate{infix}", f"{100 * r['halluc_rate']:.1f}")
        modes = r.get("failure_modes", {})
        define(f"pos{infix}", str(r["n"] - modes.get("valid", 0)
                                 - modes.get("valid_nocall", 0)))
        for m, v in modes.items():
            define(f"mode{infix}{clean(m).capitalize()}", str(v))

    # ── detector x run x subset ─────────────────────────────────────────────
    for tag, infix in RUNS.items():
        r = runs.get(tag)
        for det, dinfix in DETECTORS.items():
            for subset, sinfix in SUBSETS.items():
                macro = f"auc{dinfix}{infix}{sinfix}"
                res = (r or {}).get("results", {}).get(det, {}).get(subset)
                ms = mean_sd(res) if res else None
                if ms is None:
                    define(macro, f"\\pending{{{dinfix}/{infix}/{sinfix}}}")
                    define(macro + "SD", f"\\pending{{sd}}")
                else:
                    define(macro, f"{ms[0]:.3f}")
                    define(macro + "SD", f"{ms[1]:.3f}")

    # ── headline aggregates ─────────────────────────────────────────────────
    # per-head vs head-averaged, on the runs where both exist
    gains = []
    for tag in runs:
        res = runs[tag]["results"]
        sub = "call_expected" if res.get("Per-head all metrics (span)", {}).get(
            "call_expected") else "semantic"
        ph = mean_sd(res.get("Per-head all metrics (span)", {}).get(sub, []))
        ha = mean_sd(res.get("Spectral per-layer (LMM)", {}).get(sub, []))
        if ph and ha:
            gains.append(ph[0] - ha[0])
    if gains:
        define("perHeadGainMean", f"{100 * np.mean(gains):.1f}")
        define("perHeadGainMin", f"{100 * np.min(gains):.1f}")
        define("perHeadGainMax", f"{100 * np.max(gains):.1f}")
        define("nRunsBothSpectral", str(len(gains)))
    else:
        for m in ("perHeadGainMean", "perHeadGainMin", "perHeadGainMax",
                  "nRunsBothSpectral"):
            define(m, f"\\pending{{{m}}}")

    define("nRuns", str(len(runs)))

    # ── counts derived from the benchmark and the validity log ──────────────
    # size of the BFCL category in which no tool applies
    irr = DATA / "bfcl_v4" / "BFCL_v4_irrelevance.json"
    if irr.exists():
        n_irr = sum(1 for line in open(irr, encoding="utf-8") if line.strip())
        # the extraction caps this category; report the number actually used
        for tag in ("llama_32_1b_bfcl", "llama_32_3b_bfcl", "qwen3_17b_bfcl"):
            r = runs.get(tag)
            if r:
                modes = r["failure_modes"]
                used = modes.get("over_trigger", 0) + modes.get("valid_nocall", 0)
                define("nIrrelevanceItems", str(used))
                break
        else:
            define("nIrrelevanceItems", str(min(n_irr, 150)))
    else:
        define("nIrrelevanceItems", "\pending{irrelevance count}")

    # records discarded because the chat template dropped the tool schemas
    bad = DATA / "pilot_v2_gemma3_1b" / "INVALID_no_tools_in_prompt.jsonl.bak"
    if bad.exists():
        n_bad = sum(1 for line in open(bad, encoding="utf-8") if line.strip())
        define("nGemmaDiscardedRecords", str(n_bad))
    else:
        define("nGemmaDiscardedRecords", "\pending{discarded records}")

    # ── theory measurement: head-disagreement (Jensen) gap ──────────────────
    jf = DATA / "theory" / "jensen_gap.json"
    if jf.exists():
        s = json.loads(jf.read_text(encoding="utf-8"))["summary"]
        define("nJensenLayers", str(s["n_layers_measured"]))
        define("combGapViolations", str(s["comb_gap_violations"]))
        define("combGapMean", f"{s['comb_gap_mean']:.3f}")
        define("combGapMin", f"{s['comb_gap_min']:.4f}")
        define("normGapViolations", str(s["norm_gap_violations"]))
        define("normGapMean", f"{s['norm_gap_mean']:.3f}")
        define("normRatioMedian", f"{s['norm_ratio_median']:.2f}")
        define("normRatioMedianPct", f"{100 * (s['norm_ratio_median'] - 1):.0f}")
        define("normRatioMax", f"{s['norm_ratio_max']:.2f}")
        define("fiedlerAlignmentMean", f"{s['fiedler_alignment_mean']:.2f}")
        define("fiedlerAlignmentMax", f"{s['fiedler_alignment_max']:.2f}")
        define("perHeadSdMean", f"{s['per_head_sd_mean']:.3f}")
        define("nJensenModels", str(len(s["models"])))
    else:
        for m in ("nJensenLayers", "combGapViolations", "combGapMean",
                  "combGapMin", "normGapViolations", "normGapMean",
                  "normRatioMedian", "normRatioMedianPct", "normRatioMax",
                  "fiedlerAlignmentMean", "fiedlerAlignmentMax",
                  "perHeadSdMean", "nJensenModels"):
            define(m, f"\pending{{{m}}}")

    # ── Corollary 2: decorrelation of the two attention families ────────────
    df = DATA / "theory" / "decorrelation.json"
    if df.exists():
        d = json.loads(df.read_text(encoding="utf-8"))
        sm = d["summary"]
        define("decorrNRuns", str(sm["n_runs"]))
        define("decorrRhoMean", f"{sm['spearman_mean']:.2f}")
        define("decorrRhoMin", f"{sm['spearman_min']:.2f}")
        define("decorrRhoMax", f"{sm['spearman_max']:.2f}")
        define("decorrResidPerHead", f"{sm['residual_per_head_mean']:.3f}")
        define("decorrResidLapEig", f"{sm['residual_lapeig_mean']:.3f}")
        define("decorrUnionGain", f"{sm['union_gain_mean']:+.3f}")
        define("decorrUnionGainMax", f"{sm['union_gain_max']:+.3f}")
        define("decorrUnionPositiveRuns", str(sm["union_gain_positive_runs"]))
        for tag, infix in RUNS.items():
            if tag in d:
                m = d[tag]["mean"]
                define(f"decorrRho{infix}", f"{m['spearman']:.2f}")
                define(f"decorrUnion{infix}", f"{m['auc_union']:.3f}")
                define(f"decorrResidPh{infix}", f"{m['auc_per_head_residualized']:.3f}")
                define(f"decorrResidLap{infix}", f"{m['auc_lapeig_residualized']:.3f}")
    else:
        for m in ("decorrNRuns", "decorrRhoMean", "decorrRhoMin", "decorrRhoMax",
                  "decorrResidPerHead", "decorrResidLapEig", "decorrUnionGain",
                  "decorrUnionGainMax", "decorrUnionPositiveRuns"):
            define(m, f"\pending{{{m}}}")

    # transfer results
    for f in sorted(DATA.glob("pilot_v2_*/transfer_from_*.json")):
        test_tag = f.parent.name.replace("pilot_v2_", "")
        train_tag = f.name.replace("transfer_from_", "").replace(".json", "")
        if test_tag not in RUNS or train_tag not in RUNS:
            continue
        tf = json.loads(f.read_text(encoding="utf-8"))
        for det, dinfix in DETECTORS.items():
            ms = mean_sd(tf.get(det, {}).get("semantic", []))
            macro = f"transfer{dinfix}{RUNS[train_tag]}To{RUNS[test_tag]}"
            define(macro, f"{ms[0]:.3f}" if ms else f"\\pending{{{macro}}}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    n_pending = sum(1 for line in lines if "\\pending" in line
                    and line.startswith("\\newcommand"))
    print(f"written -> {OUT}")
    print(f"  {len(defined)} macros, {n_pending} pending, {len(runs)} runs")


if __name__ == "__main__":
    main()
