"""
Generate paper/iclr/generated_numbers.tex from the result files.

Every number in the paper resolves to a macro defined here, so no value is
typed by hand into the text. A macro that has no backing result file is
defined as \pending{...}, which renders visibly in the PDF, so a missing
experiment cannot be mistaken for a reported one.

Usage:  python analysis/make_paper_numbers.py
"""
import json
import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "paper" / "iclr" / "generated_numbers.tex"

# run tag -> macro infix
RUNS = {
    "llama_32_1b": "LlamaOneBGlaive",
    "llama_32_3b": "LlamaThreeBGlaive",
    "qwen35_2b": "QwenHybridGlaive",
    "gemma3_1b": "GemmaGlaive",
    "llama_32_1b_bfcl": "LlamaOneBBfcl",
    "llama_32_3b_bfcl": "LlamaThreeBBfcl",
    "qwen3_17b_bfcl": "QwenDenseBfcl",
    # 2026 models and the third data distribution
    "minicpm5_2b_bfcl": "MiniCpmBfcl",
    "minicpm5_2b_live": "MiniCpmLive",
    "qwen35_4b_bfcl": "QwenFourBBfcl",
    "qwen35_08b_bfcl": "QwenSmallBfcl",
    "llama1b_live": "LlamaOneBLive",
    # runs carrying the extra baseline families
    "base_llama1b_bfcl": "BaseLlamaOneBBfcl",
    "base_llama3b_bfcl": "BaseLlamaThreeBBfcl",
    "base_llama1b_glaive": "BaseLlamaOneBGlaive",
}

# detector row -> macro infix
DETECTORS = {
    "Hidden token-role [LR]": "HiddenLR",
    "Hidden token-role [MLP]": "HiddenMLP",
    "Hidden Gram spectra (EigenScore)": "EigenScore",
    "LapEigvals (official code)": "LapEigvals",
    "Per-head all metrics (span)": "PerHeadAll",
    "Per-head fiedler_value (span)": "PerHeadFiedler",
    "Per-head lambda_max (span)": "PerHeadLmax",
    "Per-head connectivity_ratio (span)": "PerHeadConn",
    "Per-head spectral_entropy_norm (span)": "PerHeadEntropy",
    "Per-head hfer (span)": "PerHeadHfer",
    "Per-head lambda_max dynamics": "PerHeadDyn",
    "Per-head lambda_max static+dynamics": "PerHeadStaticDyn",
    "All attention-spectral combined": "AttnCombined",
    "Spectral per-layer (LMM)": "HeadAveragedLayer",
    "Spectral trajectory (SpRich)": "HeadAveragedTraj",
    "Spectral velocity": "HeadAveragedVel",
    "Sym-Laplacian eig profile": "SymEigProfile",
    "Mean logprob": "Logprob",
    "Surface (lengths) [confound]": "SurfaceConfound",
    "Gen length only [confound]": "LengthConfound",
    "Tool one-hot [confound]": "ToolConfound",
    "Best single spectral (honest sweep)": "HonestSweep",
    "Token-level probe (Obeso)": "TokenProbe",
    "Residual dynamics (ICR-style)": "ResDynamics",
    "Lookback Lens": "Lookback",
}

SUBSETS = {"all": "All", "semantic": "Sem", "call_expected": "Call"}



_DIGIT_WORDS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
                "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}


def macro_key(text):
    """A LaTeX-legal macro fragment: letters only, digits spelt out."""
    out = []
    for ch in text:
        if ch.isalpha():
            out.append(ch)
        elif ch.isdigit():
            out.append(_DIGIT_WORDS[ch])
    return "".join(out)


def clean(name: str) -> str:
    """Macro-safe infix."""
    return re.sub(r"[^A-Za-z]", "", name)


def mean_sd(vals):
    vals = [v for v in vals if v is not None and not (isinstance(v, float) and np.isnan(v))]
    if not vals:
        return None
    return float(np.mean(vals)), float(np.std(vals))


def main():
    lines = [
        "% Auto-generated by paper/make_numbers.py. Do not edit by hand.",
        "% Macros without a backing result file expand to \\pending{}.",
        "\\providecommand{\\pending}[1]{\\textbf{[PENDING: #1]}}",
        "",
    ]
    defined = set()

    def define(name, value):
        if name in defined:
            return
        defined.add(name)
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    runs = {}
    for tag in RUNS:
        f = DATA / f"pilot_v2_{tag}" / "results.json"
        if f.exists():
            runs[tag] = json.loads(f.read_text(encoding="utf-8"))

    # ── per-run characterization ────────────────────────────────────────────
    for tag, infix in RUNS.items():
        r = runs.get(tag)
        if r is None:
            define(f"n{infix}", f"\\pending{{{tag} N}}")
            define(f"rate{infix}", f"\\pending{{{tag} rate}}")
            continue
        define(f"n{infix}", str(r["n"]))
        define(f"rate{infix}", f"{100 * r['halluc_rate']:.1f}")
        modes = r.get("failure_modes", {})
        define(f"pos{infix}", str(r["n"] - modes.get("valid", 0)
                                 - modes.get("valid_nocall", 0)))
        for m, v in modes.items():
            define(f"mode{infix}{clean(m).capitalize()}", str(v))

    # ── detector x run x subset ─────────────────────────────────────────────
    for tag, infix in RUNS.items():
        r = runs.get(tag)
        for det, dinfix in DETECTORS.items():
            for subset, sinfix in SUBSETS.items():
                macro = f"auc{dinfix}{infix}{sinfix}"
                res = (r or {}).get("results", {}).get(det, {}).get(subset)
                ms = mean_sd(res) if res else None
                if ms is None:
                    define(macro, f"\\pending{{{dinfix}/{infix}/{sinfix}}}")
                    define(macro + "SD", f"\\pending{{sd}}")
                else:
                    define(macro, f"{ms[0]:.3f}")
                    define(macro + "SD", f"{ms[1]:.3f}")

    # ── headline aggregates ─────────────────────────────────────────────────
    # per-head vs head-averaged, on the runs where both exist
    # only the runs the tables report; superseded runs and the re-extractions
    # made for the confidence summaries would count a model twice
    TABLE_TAGS = {"base_llama1b_glaive", "base_llama3b_glaive", "base_gemma3_glaive",
                  "base_llama1b_bfcl", "base_llama3b_bfcl", "base_qwen3_17b_bfcl",
                  "minicpm5_2b_bfcl", "qwen35_08b_bfcl", "qwen35_4b_bfcl",
                  "qwen35_2b", "llama1b_live", "minicpm5_2b_live"}
    gains = []
    for tag in runs:
        if tag not in TABLE_TAGS:
            continue
        res = runs[tag]["results"]
        sub = "call_expected" if res.get("Per-head all metrics (span)", {}).get(
            "call_expected") else "semantic"
        ph = mean_sd(res.get("Per-head all metrics (span)", {}).get(sub, []))
        ha = mean_sd(res.get("Spectral per-layer (LMM)", {}).get(sub, []))
        if ph and ha:
            gains.append(ph[0] - ha[0])
    if gains:
        define("perHeadGainMean", f"{100 * np.mean(gains):.1f}")
        define("perHeadGainMin", f"{100 * np.min(gains):.1f}")
        define("perHeadGainMax", f"{100 * np.max(gains):.1f}")
        define("nRunsBothSpectral", str(len(gains)))
    else:
        for m in ("perHeadGainMean", "perHeadGainMin", "perHeadGainMax",
                  "nRunsBothSpectral"):
            define(m, f"\\pending{{{m}}}")

    define("nRuns", str(len(runs)))

    # ── counts derived from the benchmark and the validity log ──────────────
    # size of the BFCL category in which no tool applies
    irr = DATA / "bfcl_v4" / "BFCL_v4_irrelevance.json"
    if irr.exists():
        n_irr = sum(1 for line in open(irr, encoding="utf-8") if line.strip())
        # the extraction caps this category; report the number actually used
        for tag in ("llama_32_1b_bfcl", "llama_32_3b_bfcl", "qwen3_17b_bfcl"):
            r = runs.get(tag)
            if r:
                modes = r["failure_modes"]
                used = modes.get("over_trigger", 0) + modes.get("valid_nocall", 0)
                define("nIrrelevanceItems", str(used))
                break
        else:
            define("nIrrelevanceItems", str(min(n_irr, 150)))
    else:
        define("nIrrelevanceItems", "\pending{irrelevance count}")

    # records discarded because the chat template dropped the tool schemas
    bad = DATA / "pilot_v2_gemma3_1b" / "INVALID_no_tools_in_prompt.jsonl.bak"
    if bad.exists():
        n_bad = sum(1 for line in open(bad, encoding="utf-8") if line.strip())
        define("nGemmaDiscardedRecords", str(n_bad))
    else:
        define("nGemmaDiscardedRecords", "\pending{discarded records}")

    # ── theory measurement: head-disagreement (Jensen) gap ──────────────────
    jf = DATA / "theory" / "jensen_gap.json"
    if jf.exists():
        s = json.loads(jf.read_text(encoding="utf-8"))["summary"]
        define("nJensenLayers", str(s["n_layers_measured"]))
        define("combGapViolations", str(s["comb_gap_violations"]))
        define("combGapMean", f"{s['comb_gap_mean']:.3f}")
        define("combGapMin", f"{s['comb_gap_min']:.4f}")
        define("normGapViolations", str(s["norm_gap_violations"]))
        define("normGapMean", f"{s['norm_gap_mean']:.3f}")
        define("normRatioMedian", f"{s['norm_ratio_median']:.2f}")
        define("normRatioMedianPct", f"{100 * (s['norm_ratio_median'] - 1):.0f}")
        define("normRatioMax", f"{s['norm_ratio_max']:.2f}")
        define("fiedlerAlignmentMean", f"{s['fiedler_alignment_mean']:.2f}")
        define("fiedlerAlignmentMax", f"{s['fiedler_alignment_max']:.2f}")
        define("perHeadSdMean", f"{s['per_head_sd_mean']:.3f}")
        define("nJensenModels", str(len(s["models"])))
    else:
        for m in ("nJensenLayers", "combGapViolations", "combGapMean",
                  "combGapMin", "normGapViolations", "normGapMean",
                  "normRatioMedian", "normRatioMedianPct", "normRatioMax",
                  "fiedlerAlignmentMean", "fiedlerAlignmentMax",
                  "perHeadSdMean", "nJensenModels"):
            define(m, f"\pending{{{m}}}")

    # ── Corollary 2: decorrelation of the two attention families ────────────
    df = DATA / "theory" / "decorrelation.json"
    if df.exists():
        d = json.loads(df.read_text(encoding="utf-8"))
        sm = d["summary"]
        define("decorrNRuns", str(sm["n_runs"]))
        define("decorrRhoMean", f"{sm['spearman_mean']:.2f}")
        define("decorrRhoMin", f"{sm['spearman_min']:.2f}")
        define("decorrRhoMax", f"{sm['spearman_max']:.2f}")
        define("decorrResidPerHead", f"{sm['residual_per_head_mean']:.3f}")
        define("decorrResidLapEig", f"{sm['residual_lapeig_mean']:.3f}")
        define("decorrUnionGain", f"{sm['union_gain_mean']:+.3f}")
        define("decorrUnionGainMax", f"{sm['union_gain_max']:+.3f}")
        define("decorrUnionPositiveRuns", str(sm["union_gain_positive_runs"]))
        for tag, infix in RUNS.items():
            if tag in d:
                m = d[tag]["mean"]
                define(f"decorrRho{infix}", f"{m['spearman']:.2f}")
                define(f"decorrUnion{infix}", f"{m['auc_union']:.3f}")
                define(f"decorrResidPh{infix}", f"{m['auc_per_head_residualized']:.3f}")
                define(f"decorrResidLap{infix}", f"{m['auc_lapeig_residualized']:.3f}")
    else:
        for m in ("decorrNRuns", "decorrRhoMean", "decorrRhoMin", "decorrRhoMax",
                  "decorrResidPerHead", "decorrResidLapEig", "decorrUnionGain",
                  "decorrUnionGainMax", "decorrUnionPositiveRuns"):
            define(m, f"\pending{{{m}}}")

    fkf = DATA / "theory" / "decorrelation_fixedk.json"
    if fkf.exists():
        fk = json.loads(fkf.read_text(encoding="utf-8"))["summary"]
        define("decorrUnionGainFixed", f"{fk['union_gain_mean']:+.3f}")
    else:
        define("decorrUnionGainFixed", "\\pending{fixed-width union}")

    lb = DATA / "theory" / "label_budget.json"
    if lb.exists():
        d = json.loads(lb.read_text(encoding="utf-8"))
        cs = d.get("cross_run_summary", {})
        if cs:
            define("budgetNRuns", str(cs["n_runs"]))
            define("budgetSpearman", f"{cs['spearman_logpos_vs_gap']:.2f}")
            define("budgetSpearmanP", f"{cs['spearman_p']:.3f}")
            define("budgetGapFew", f"{cs['gap_few_positives']:+.3f}")
            define("budgetGapMany", f"{cs['gap_many_positives']:+.3f}")
        rows = d.get("cross_run", [])
        for r in rows:
            tag = r["run"]
            if tag in RUNS:
                define(f"pos{RUNS[tag]}Count", str(r["positives"]))
                define(f"gap{RUNS[tag]}", f"{r['gap']:+.3f}")
                define(f"conf{RUNS[tag]}", f"{r['confidence']:.3f}")
                define(f"probe{RUNS[tag]}", f"{r['probe']:.3f}")
        neg = [r for r in rows if r["gap"] < 0]
        if neg:
            define("budgetNegRuns", str(len(neg)))
            define("budgetNegMaxPos", str(max(r["positives"] for r in neg)))
        for tag, curve in d.get("curve", {}).items():
            if tag not in RUNS or not curve:
                continue
            infix = RUNS[tag]
            define(f"curve{infix}Low", f"{curve[0]['auc']:.3f}")
            define(f"curve{infix}LowPos", str(curve[0]["approx_train_positives"]))
            define(f"curve{infix}Full", f"{curve[-1]['auc']:.3f}")
            define(f"curve{infix}FullPos", str(curve[-1]["approx_train_positives"]))
            define(f"curve{infix}Drop",
                   f"{curve[-1]['auc'] - curve[0]['auc']:.3f}")
    else:
        for m in ("budgetNRuns", "budgetSpearman", "budgetSpearmanP",
                  "budgetGapFew", "budgetGapMany", "budgetNegRuns",
                  "budgetNegMaxPos"):
            define(m, f"\\pending{{{m}}}")

    rl = DATA / "theory" / "resolution_ladder.json"
    if rl.exists():
        d = json.loads(rl.read_text(encoding="utf-8"))
        sm = d["summary"]
        define("ladNRuns", str(len(d["runs"])))
        rung_macros = {
            "graph-averaged (L x 5)": "ladGraphAvg",
            "metric-averaged (L x 5)": "ladMetricAvg",
            "per-head (L x H x 5)": "ladPerHead",
            "noise-padded graph-averaged (L x H x 5)": "ladNoisePadded",
            "head-shuffled per-head (L x H x 5)": "ladHeadShuffled",
            "1 random heads (L x 1 x 5)": "ladOneHead",
            "2 random heads (L x 2 x 5)": "ladTwoHeads",
            "4 random heads (L x 4 x 5)": "ladFourHeads",
            "8 random heads (L x 8 x 5)": "ladEightHeads",
        }
        for rung, macro in rung_macros.items():
            if rung in sm:
                define(macro, f"{sm[rung]['mean']:.3f}")
        for key, macro in (("metric_avg_minus_graph_avg", "ladGainMetricAvg"),
                           ("per_head_minus_metric_avg", "ladGainPerHead"),
                           ("per_head_minus_noise_padded", "ladGainVsNoise"),
                           ("per_head_minus_head_shuffled", "ladGainVsShuffle"),
                           ("noise_padded_minus_graph_avg", "ladNoiseEffect")):
            c = sm["contrasts"][key]
            define(macro, f"{c['mean']:+.3f}")
            define(macro + "Pos", str(c["positive_runs"]))
            define(macro + "Min", f"{c['min']:+.3f}")
            define(macro + "Max", f"{c['max']:+.3f}")
        # per-run values for the ladder table
        for tag, r in d["runs"].items():
            key = macro_key("".join(
                w.capitalize() for w in tag.replace("base_", "").split("_")))
            for rung, macro in rung_macros.items():
                if rung in r["auc"]:
                    define(f"{macro}{key}", f"{r['auc'][rung]['mean']:.3f}")
    else:
        for m in ("ladNRuns", "ladGraphAvg", "ladMetricAvg", "ladPerHead",
                  "ladNoisePadded", "ladHeadShuffled", "ladGainMetricAvg",
                  "ladGainMetricAvgPos", "ladGainPerHead", "ladGainVsNoise",
                  "ladGainVsShuffle", "ladNoiseEffect", "ladOneHead",
                  "ladTwoHeads", "ladFourHeads", "ladEightHeads"):
            define(m, f"\\pending{{{m}}}")

    dg = DATA / "theory" / "diag_fusion_pooling.json"
    if dg.exists():
        d = json.loads(dg.read_text(encoding="utf-8"))
        for tag, infix in (("base_llama1b_glaive", "LlamaOneBGlaive"),
                           ("base_llama3b_glaive", "LlamaThreeBGlaive"),
                           ("base_llama1b_bfcl", "LlamaOneBBfcl")):
            if tag not in d:
                continue
            r = d[tag]
            for k, name in (("hidden", "Hidden"), ("per_head", "PerHead"),
                            ("mean", "Mean"), ("rank_mean", "RankMean")):
                define(f"poolPooled{name}{infix}", f"{r['pooled'][k]:.3f}")
                define(f"poolWithin{name}{infix}",
                       f"{r['within_fold_mean'][k]:.3f}")
        # the pooling cost of the residual probe, averaged over the runs
        costs = [d[t]["within_fold_mean"]["hidden"] - d[t]["pooled"]["hidden"]
                 for t in d]
        define("poolCostHiddenMean", f"{sum(costs) / len(costs):.3f}")
        define("poolNRuns", str(len(d)))
    else:
        for m in ("poolCostHiddenMean", "poolNRuns"):
            define(m, f"\\pending{{{m}}}")

    fs = DATA / "theory" / "family_split.json"
    if fs.exists():
        d = json.loads(fs.read_text(encoding="utf-8"))
        for subset, infix in (("semantic", "Sem"), ("call_expected", "Call")):
            if subset not in d:
                continue
            q = d[subset]["summary"]
            define(f"famNRuns{infix}", str(q["n_runs"]))
            define(f"famNRecent{infix}", str(q["n_recent"]))
            define(f"famNEarlier{infix}", str(q["n_earlier"]))
            define(f"famGapRecent{infix}", f"{q['gap_recent_mean']:+.3f}")
            define(f"famGapEarlier{infix}", f"{q['gap_earlier_mean']:+.3f}")
            define(f"famRecentMax{infix}", f"{q['gap_recent_max']:+.3f}")
            define(f"famEarlierMin{infix}", f"{q['gap_earlier_min']:+.3f}")
            define(f"famMannWhitney{infix}", f"{q['mannwhitney_p']:.4f}")
            define(f"famConfWins{infix}", str(q["confidence_wins_recent"]))
            define(f"famSpearman{infix}", f"{q['spearman_logpos_vs_gap']:.2f}")
            define(f"famSpearmanP{infix}", f"{q['spearman_p']:.2f}")
            if "spearman_within_recent" in q:
                define(f"famWithinRecent{infix}",
                       f"{q['spearman_within_recent']:+.2f}")
            if "spearman_within_earlier" in q:
                define(f"famWithinEarlier{infix}",
                       f"{q['spearman_within_earlier']:+.2f}")
            # one observation per checkpoint and per family, which are the
            # units the claim is about; runs sharing a checkpoint are not
            # independent
            if "n_checkpoints" in q:
                define(f"famNCkpt{infix}", str(q["n_checkpoints"]))
                define(f"famNCkptRecent{infix}", str(q["n_checkpoints_recent"]))
                define(f"famNCkptEarlier{infix}", str(q["n_checkpoints_earlier"]))
            if "checkpoint_mannwhitney_p" in q:
                define(f"famCkptMannWhitney{infix}",
                       f"{q['checkpoint_mannwhitney_p']:.3f}")
            if "family_gaps" in q:
                define(f"famNFamilies{infix}", str(q["n_families"]))
                for fam, gap in q["family_gaps"].items():
                    define(f"famGap{macro_key(fam)}{infix}", f"{gap:+.3f}")
    else:
        for m in ("famNRunsSem", "famGapRecentSem", "famGapEarlierSem",
                  "famMannWhitneySem"):
            define(m, f"\\pending{{{m}}}")

    cv = DATA / "theory" / "confidence_variants.json"
    if cv.exists():
        d = json.loads(cv.read_text(encoding="utf-8"))
        alias = {"conf_llama1b_bfcl": "CvLlamaBfcl",
                 "conf_llama1b_glaive": "CvLlamaGlaive",
                 "conf_minicpm_bfcl": "CvMiniCpmBfcl"}
        for tag, infix in alias.items():
            if tag not in d:
                continue
            q = d[tag]
            define(f"{infix}Probe", f"{q['probe_auc']:.3f}")
            define(f"{infix}MeanLp", f"{q['mean_logprob_auc']:.3f}")
            define(f"{infix}Best", f"{q['best_genuine_auc']:.3f}")
            define(f"{infix}BestName",
                   q["best_genuine"].replace("_", " "))
            define(f"{infix}Surface", f"{q['surface_auc']:.3f}")
            define(f"{infix}GapMean", f"{q['gap_mean_logprob']:+.3f}")
            define(f"{infix}GapBest", f"{q['gap_best_confidence']:+.3f}")
            define(f"{infix}NSummaries", str(len(q["all_confidence"])))
            sl = q["all_confidence"].get("Confidence: sum_logprob")
            if sl is not None:
                define(f"{infix}SumLp", f"{sl:.3f}")
    else:
        for m in ("CvLlamaBfclProbe", "CvLlamaBfclBest", "CvMiniCpmBfclBest"):
            define(m, f"\\pending{{{m}}}")

    fo = DATA / "theory" / "fusion_operating.json"
    if fo.exists():
        d = json.loads(fo.read_text(encoding="utf-8"))
        q = d.get("summary", {})
        if q:
            define("agrNRuns", str(q["n_runs"]))
            define("agrBothPrec", f"{q['both_prec_mean']:.3f}")
            define("agrBothRec", f"{q['both_rec_mean']:.3f}")
            define("agrEitherPrec", f"{q['either_prec_mean']:.3f}")
            define("agrEitherRec", f"{q['either_rec_mean']:.3f}")
            define("agrSinglePrec", f"{q['hidden_prec80_mean']:.3f}")
            define("agrStackGain", f"{q['stack_auc_gain_mean']:+.3f}")
            define("agrStackPositive", str(q["stack_auc_positive_runs"]))
            define("agrStackPrecGain", f"{q['stack_prec80_gain_mean']:+.3f}")
            if "stack_rank_auc_gain_mean" in q:
                define("agrStackRankGain", f"{q['stack_rank_auc_gain_mean']:+.3f}")
                define("agrStackRankGainMax", f"{q['stack_rank_auc_gain_max']:+.3f}")
                define("agrStackRankPositive", str(q["stack_rank_auc_positive_runs"]))
                define("agrStackRankPrecGain",
                       f"{q['stack_rank_prec80_gain_mean']:+.3f}")
            define("agrMatchedGain", f"{q['both_prec_gain_matched_mean']:+.3f}")
            define("agrMatchedPositive",
                   str(q["both_prec_gain_matched_positive"]))
            define("agrBaseMin", f"{100 * q['base_rate_min']:.0f}")
            define("agrBaseMax", f"{100 * q['base_rate_max']:.0f}")
        best = None
        for tag, v in d.items():
            if tag == "summary":
                continue
            m = v["mean"]
            if best is None or m["prec_both"] > best[1]:
                best = (tag, m["prec_both"], m["rec_both"])
        if best:
            define("agrBestRun", best[0].replace("_", " "))
            define("agrBestPrec", f"{best[1]:.3f}")
            define("agrBestRec", f"{best[2]:.3f}")
    else:
        for m in ("agrNRuns", "agrBothPrec", "agrBothRec", "agrSinglePrec"):
            define(m, f"\\pending{{{m}}}")

    # transfer results
    for f in sorted(DATA.glob("pilot_v2_*/transfer_from_*.json")):
        test_tag = f.parent.name.replace("pilot_v2_", "")
        train_tag = f.name.replace("transfer_from_", "").replace(".json", "")
        if test_tag not in RUNS or train_tag not in RUNS:
            continue
        tf = json.loads(f.read_text(encoding="utf-8"))
        for det, dinfix in DETECTORS.items():
            ms = mean_sd(tf.get(det, {}).get("semantic", []))
            macro = f"transfer{dinfix}{RUNS[train_tag]}To{RUNS[test_tag]}"
            define(macro, f"{ms[0]:.3f}" if ms else f"\\pending{{{macro}}}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    n_pending = sum(1 for line in lines if "\\pending" in line
                    and line.startswith("\\newcommand"))
    print(f"written -> {OUT}")
    print(f"  {len(defined)} macros, {n_pending} pending, {len(runs)} runs")


if __name__ == "__main__":
    main()
